apiVersion: v1
kind: ConfigMap
metadata:
  name: convert-service-config
  namespace: convert-service
  labels:
    app.kubernetes.io/name: convert-service
    app.kubernetes.io/part-of: pm4-6558-d4
data:
  APP_NAME: currency-convert
  LOG_LEVEL: INFO
  SUPPORTED_CURRENCIES: "USD,EUR,GBP,INR"
